services:
  gnu-cash:
    build:
      # if compose file is included, context is directory of parent compose file
      context: .
      # dockerfile is with respect to context directory
      dockerfile: "./Dockerfile"
      args:
        DOCKER_BASE_IMAGE_NAME: ${DOCKER_BASE_IMAGE_NAME}
        DOCKER_BASE_IMAGE_TAG: ${DOCKER_BASE_IMAGE_TAG}
        USERNAME: ${DOCKER_USERNAME}
        USER_UID: ${DOCKER_USER_UID}
        USER_GID: ${DOCKER_USER_GID}
    environment:
      DISPLAY: ${DISPLAY}
      # https://unix.stackexchange.com/questions/230238/x-applications-warn-couldnt-connect-to-accessibility-bus-on-stderr
      NO_AT_BRIDGE: 1
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4g
        reservations:
          cpus: 4
          memory: 4g
    volumes:
      - type: bind
        source: /tmp/.X11-unix/
        target: /tmp/.X11-unix/
        read_only: true
      - type: bind
        source: storage/gnucash_user_data/
        target: /home/${DOCKER_USERNAME}/gnucash_user_data
      - type: bind
        source: storage/share/gnucash/
        target: /home/${DOCKER_USERNAME}/.local/share/gnucash/
      - type: bind
        source: storage/config/gnucash
        target: /home/${DOCKER_USERNAME}/.config/gnucash
      - type: bind
        source: storage/config/dconf
        target: /home/${DOCKER_USERNAME}/.config/dconf