services:
  gnu-cash:
    build:
      # if compose file is included, context is directory of parent compose file
      context: .
      # dockerfile is with respect to context directory
      dockerfile: "./Dockerfile"
      args:
        CONTAINER_BASE_IMAGE_NAME: ${CONTAINER_BASE_IMAGE_NAME}
        CONTAINER_BASE_IMAGE_TAG: ${CONTAINER_BASE_IMAGE_TAG}
        USERNAME: ${CONTAINER_USERNAME}
        USER_UID: ${CONTAINER_USER_UID}
        USER_GID: ${CONTAINER_USER_GID}
    environment:
      DISPLAY: ${DISPLAY}
      # https://unix.stackexchange.com/questions/230238/x-applications-warn-couldnt-connect-to-accessibility-bus-on-stderr
      NO_AT_BRIDGE: 1
      ALSA_CONFIG_PATH: /dev/null
    user: "${CONTAINER_USER_UID}:${CONTAINER_USER_GID}"
    userns_mode: "keep-id:uid=${CONTAINER_USER_UID},gid=${CONTAINER_USER_GID}"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4g
        reservations:
          cpus: 4
          memory: 4g
    volumes:
      - type: bind
        source: /tmp/.X11-unix/
        target: /tmp/.X11-unix/
        read_only: true
      - type: bind
        source: ./storage/gnucash_user_data/
        target: /home/${CONTAINER_USERNAME}/gnucash_user_data
      - type: bind
        source: ./storage/share/gnucash/
        target: /home/${CONTAINER_USERNAME}/.local/share/gnucash/
      - type: bind
        source: ./storage/config/gnucash
        target: /home/${CONTAINER_USERNAME}/.config/gnucash
      - type: bind
        source: ./storage/config/dconf
        target: /home/${CONTAINER_USERNAME}/.config/dconf